# Generated by Django 4.0.4 on 2024-03-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodified',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='users/profile_pictures'),
        ),
        migrations.AddField(
            model_name='usermodified',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
