# Generated by Django 4.0.4 on 2024-03-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_usermodified_profile_picture_usermodified_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodified',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile_pictures'),
        ),
        migrations.AlterField(
            model_name='usermodified',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
