# Generated by Django 4.0.4 on 2024-03-16 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_product_price_after_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpicture',
            options={'verbose_name': 'Product picture', 'verbose_name_plural': 'Product pictures'},
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attribute_name', to='application.productattribute'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attributes', to='application.product'),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pictures', to='application.product'),
        ),
    ]
