# Generated by Django 4.0.4 on 2024-03-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_productpicture_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_created'], 'verbose_name': 'product', 'verbose_name_plural': 'product'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_creating',
            new_name='date_created',
        ),
    ]
