# Generated by Django 4.2.7 on 2024-06-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_cart_session_token_alter_cart_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_id',
            new_name='cart',
        ),
    ]
