# Generated by Django 4.2.7 on 2024-06-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_rename_cart_id_cartitem_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='wishlist_id',
            new_name='wishlist',
        ),
    ]
