# Generated by Django 4.2.7 on 2024-06-16 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_rename_product_id_cartitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
